pactus-project/PIPs

_includes/head.html
_layouts/pip.html
config/.jekyll-labels.yml
config/pip-editors.yml
pip-template.md
rss/nonerc-last-call.xml
rss/nonerc.xml
rss/pip-last-call.xml

fix: replace pip with erc

---

_includes/head.html
_layouts/pip.html
config/.jekyll-labels.yml
config/pip-editors.yml
pip-template.md
rss/nonerc-last-call.xml
rss/nonerc.xml
rss/pip-last-call.xml

@Ja7ad please fix the comments on https://github.com/pactus-project/PIPs/pull/6

Revert "fix: replace pip with erc"

---

PIPs/pip-7.md

This PR updates PIP-7 for better clarity.

chore: updating pip-7

---

PIPs/pip-3.md
PIPs/pip-4.md
PIPs/pip-5.md
PIPs/pip-6.md
PIPs/pip-7.md

Based on the example `Template` guides.

Use Standards Track instead of Standard(s)

---

PIPs/pip-5.md

Change pip-5 status

---

PIPs/pip-8.md

This PR updates the title of PIP-8

updating pip-8 title

---

PIPs/pip-11.md
assets/pip-11/testvectors.py
config/.markdownlint.yaml

This PR introduces the PIP-11.

introducing the pip-11

---

PIPs/pip-11.md

This PR updates the title of PIP-11.

updating the title

---

PIPs/pip-2.md
PIPs/pip-3.md

Removing stamp from the PIP, since it has no documentation anymore.

updating pip-3

---

PIPs/pip-2.md
PIPs/pip-7.md

This PR updated PIP-7 for better clarity.

updating pip-7

---

PIPs/pip-15.md

This PR introduces PIP-15 to apply the proposed changes to the store module.

adding pip-15

---

PIPs/pip-10.md

Implemented By: https://github.com/pactus-project/pactus/pull/837

accepted pip-10

---

PIPs/pip-13.md

chore: update pip-13 status

---

PIPs/pip-17.md

Fixing PIP-17 yaml headers issue

---

PIPs/pip-18.md

When opening a pull request to submit a new PIP, please use the suggested template: https://github.com/pactus-project/PIPs/blob/master/pip-template.md
We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:
- The PR edits only existing draft PRs.
- The build passes.
- Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
- If matching on email address, the email address is the one publicly listed on your GitHub profile.

Time Check Proposal

---

PIPs/pip-15.md

updating pip-15

---

PIPs/pip-19.md

updating pip-19

---

PIPs/pip-19.md
_config.yml

This PR tries to address the issue where block math formulas are not rendering correctly using LaTeX.

chore: try fixing math issue (latex)

---

PIPs/pip-10.md

updating pip-10

---

PIPs/pip-21.md

unbond token can rebond at any time.

Create pip-21.md [unbond token can rebond at any time.]

---

PIPs/pip-22.md

* Added PIP22 to resolve client agent pattern in GUI for windows

Added PIP22 to resolve client agent pattern in GUI for windows

---

PIPs/pip-20.md

Implementation https://github.com/pactus-project/pactus/pull/1162

chore: update pip status to final

---

PIPs/pip-15.md

This PR fixes a typo and explains the PairSlice

fix a typo and explain pair-slice

---

PIPs/pip-23.md

Sign and verify message by public and private key account

feat: add pip-23

---

_includes/head.html
_includes/header.html
assets/css/style.scss
assets/js/color-modes.js

feat: add theme toggle

---

PIPs/pip-11.md

The PIP-11 is implemented and can be check for the final review.

PIP-11: Accepted  

---

PIPs/pip-12.md

This PR rejects PIP-12, check discussion for more information.

PIP-12: Rejected

---

PIPs/pip-18.md

PIP-18: Updated and ready for the implementation

---

PIPs/pip-12.md

PIP-12: update the status

---

PIPs/pip-24.md

This PR starts discussing for: "Change Proposer on Double Proposing"

PIP-24: Drafting Pip-24

---

PIPs/pip-18.md

PIP-18: update the proposal

---

.github/workflows/ci.yml
.github/workflows/jekyll-label-bot.yml
README.md

This PR updates README and GitHub actions

update readme and github actions

---

PIPs/pip-26.md

This PR drafts the PIP-26 to calculate Minimum Availability Score

PIP-26: Minimum Availability Score

---

_includes/head.html

This PR tries to show Math on both inline and display blocks

fix MathJax inline and display math issues

---

PIPs/pip-18.md
PIPs/pip-19.md
PIPs/pip-20.md
PIPs/pip-21.md
PIPs/pip-23.md
PIPs/pip-24.md
PIPs/pip-25.md
PIPs/pip-26.md
pip-template.md

Fix some mistakes related to #126

fix mistakes on previous PR

---

pip-template.md

This PR adds category to the PIP template.

add category to PIP template

---

PIPs/pip-24.md

PIP-24: withdraw the PIP

---

PIPs/pip-10.md

PIP-10: withdraw the PIP

---

_includes/piptable.html
_layouts/pip.html

This PR:
- Removes discussion link from the table
- Set properer link and target for discussion link in PIP page

update discussion links

---

PIPs/pip-27.md

This PR updates the spec for PIP-27

PIP-27: update the spec

---

PIPs/pip-11.md
PIPs/pip-13.md
README.md
_config.yml
config/.jekyll-labels.yml
pip-template.md
wallet.html

feat: add category wallet

---

PIPs/pip-27.md

If not have issue, at 1:30 PM UTC this proposal will accepted.

docs: accepted pip-27 for implementation

---

PIPs/pip-27.md

This PR removes the check on imported data. Check discussion-link for more information.

PIP-27: remove import data verification

---

PIPs/pip-16.md
PIPs/pip-17.md
PIPs/pip-4.md
PIPs/pip-5.md
PIPs/pip-7.md
PIPs/pip-8.md

I've just changed my email to a self-hosted email, and decided to change it here as well.

Change kay emails

---

PIPs/pip-32.md

When opening a pull request to submit a new PIP, please use the suggested template: https://github.com/pactus-project/PIPs/blob/master/pip-template.md
We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:
- The PR edits only existing draft PRs.
- The build passes.
- Your GitHub username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
- If matching on email address, the email address is the one publicly listed on your GitHub profile.

fix: pip number

---

PIPs/pip-31.md

This PR update the consumptional Fee Model...

PIP-32: update the consumptional fee formula

---

.github/workflows/ci.yml
PIPs/pip-1.md
_config.yml

Support mermaid workflow

---

Makefile
PIPs/pip-1.md

[PIP-1] update for template and diagram

---

PIPs/pip-31.md

This PR updates the PIP-31 and explain the pending consumption.

PIP-31: add pending consumptions

---

.github/workflows/ci.yml
PIPs/pip-1.md
_config.yml

This PR removes the mermaid chart.

remove mermaid chart

---

PIPs/pip-35.md

Here, in this PR, we have a compare list of some communication protocols to use in the Pactus blockchain. These protocols have been compared by simplicity, resource consumption, implementation, and community size.

PIP-35: Comparison of communication protocols

---

PIPs/pip-35.md

This update includes a comparison of protocols around brokers and also some edits in the conclusion part of PIP.

PIP-35: comparison of protocols around using broker

---

PIPs/pip-35.md

The PIP status can change to "final"
Thanks @akbariandev  for this great work.

PIP32: update the status to final

---

index.html

This PR removes the social links from the front page

remove social links

---

PIPs/pip-36.md

pip-36: change status to final

---

PIPs/pip-37.md

PIP-37: update the PIP

---

PIPs/pip-38.md

This PIP suggest a safe mechanism to monitor the Xeggex deposit account.

PIP-38: Monitor Xeggex deposit account

---

PIPs/pip-38.md

Update the PIP for better clarity

PIP-38: Update the PIP for better clarity

---

PIPs/pip-38.md

As the community requested, look [here](https://x.com/PactusChain/status/1893327634735530267), we have successfully unfrozen the Xeggex account with a single [transaction](https://pacviewer.com/transaction/1cbd5fdfdf3ff5bcb7cdb1b729dcd7a3bc62c6b06415905505aaf4ace8db37ce), without any software update. 
This PIP can be withdrawn since it was not a major update release.

pip-38: change status

---

PIPs/pip-37.md

fix: add upgrade version to 0x02

---

PIPs/pip-39.md

chore: add discussion-no

---

PIPs/pip-40.md

pip-40: realloaction of network fees to treasury

---

PIPs/pip-41.md

This PR adds the PIP-40 for address recovery

pip-41: add Address Recovery PIP

---

PIPs/pip-37.md

PIP-37 replaces and Withdrawn with PIP-39

Withdrawn  pip-37.md

---

PIPs/pip-39.md

PIP-39: set status to Final

---

PIPs/pip-43.md

chore: add discussion number for pip 43

---

PIPs/pip-32.md
PIPs/pip-43.md

PIP-43- update status to final

---

PIPs/pip-1.md
PIPs/pip-10.md
PIPs/pip-12.md
PIPs/pip-20.md
PIPs/pip-40.md
PIPs/pip-6.md
PIPs/pip-7.md
PIPs/pip-8.md
README.md
pip-template.md

Fix some typos and grammar issues

fix some typos

---

.github/workflows/ci.yml
Makefile
PIPs/pip-42.md

fix broken links

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml
_layouts/pip.html

This PR updates the linting action

update linting action

---

PIPs/pip-41.md

Change status from Draft to Accepted

---

PIPs/pip-41.md

PIP-41- update PIP
